/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.pos.controller.AdminController;
import lk.ijse.pos.dto.AdminDTO;

/**
 *
 * @author DEll
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        pnlNewAdmin.setVisible(false);
        lblReception.setBackground(new Color(54, 215, 183, 100));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReception = new javax.swing.JLabel();
        lblCloseH1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        pnlNewAdmin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnAdd = new javax.swing.JButton();
        lblCloseH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReception.setBackground(new java.awt.Color(82, 179, 217));
        lblReception.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReception.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/receptionist-icon.png 128.png"))); // NOI18N
        lblReception.setText("Receptionist");
        lblReception.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        lblReception.setOpaque(true);
        lblReception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReceptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReceptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReceptionMouseExited(evt);
            }
        });
        jPanel1.add(lblReception, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 270, 140));

        lblCloseH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Error-icon.png"))); // NOI18N
        lblCloseH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseExited(evt);
            }
        });
        jPanel1.add(lblCloseH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 30, 30));

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin Portal");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 890, 50));

        lblSettings.setBackground(new java.awt.Color(102, 255, 153));
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-services-48.png"))); // NOI18N
        lblSettings.setToolTipText("Settings");
        lblSettings.setOpaque(true);
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });
        jPanel1.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 60, 70));

        pnlNewAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Admin Name");
        pnlNewAdmin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Password");
        pnlNewAdmin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Confirm Password");
        pnlNewAdmin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 20));

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, 30));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 30));

        lblCloseH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Error-icon.png"))); // NOI18N
        lblCloseH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseHMouseEntered(evt);
            }
        });
        pnlNewAdmin.add(lblCloseH, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 30));

        jPanel1.add(pnlNewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 290, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/36675951524_19e54786dd_b.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 890, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblReceptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReceptionMouseClicked
        AddReceptionForm d = new AddReceptionForm();
        this.setVisible(false);
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReceptionMouseClicked

    private void lblReceptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReceptionMouseEntered
        lblReception.setSize(280,150);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReceptionMouseEntered

    private void lblReceptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReceptionMouseExited
        lblReception.setSize(270,140);
    }//GEN-LAST:event_lblReceptionMouseExited

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        pnlNewAdmin.setVisible(true);
        txtName.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void lblCloseHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseHMouseClicked
        pnlNewAdmin.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseHMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        txtPassword.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        btnAdd.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        txtConfirmPassword.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println(txtPassword.getText());
        AdminDTO adminDTO = new AdminDTO(txtName.getText(),
                txtPassword.getText());
        System.out.println("2");
        try {
            boolean result = false;
            if (txtPassword.getText().equals(txtConfirmPassword.getText())) {
                result = AdminController.addAdmin(adminDTO);
                System.out.println("admin");
                result = true;

                if (result) {
                    JOptionPane.showMessageDialog(this, "Admin added successfully");
                    txtName.setText("");
                    txtPassword.setText("");
                    txtConfirmPassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Admin not added successfully");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Wrong confirm Password");
                txtConfirmPassword.setText("");
                txtPassword.setText("");
            }

        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
         } else {
                
         }
         */
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void lblCloseH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseH1MouseClicked

    private void lblCloseH1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseEntered
        lblCloseH1.setSize(40,40);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseH1MouseEntered

    private void lblCloseH1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseExited
        lblCloseH1.setSize(30,30);
    }//GEN-LAST:event_lblCloseH1MouseExited

    private void lblCloseHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseHMouseEntered
        lblCloseH1.setSize(40,40);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseHMouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited
        lblSettings.setSize(60,70);
    }//GEN-LAST:event_lblSettingsMouseExited

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        lblSettings.setSize(70,80);
    }//GEN-LAST:event_lblSettingsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCloseH;
    private javax.swing.JLabel lblCloseH1;
    private javax.swing.JLabel lblReception;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JPanel pnlNewAdmin;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
