/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import lk.ijse.pos.Observer.Observer;
import lk.ijse.pos.controller.AppointmentController;

/**
 *
 * @author DEll
 */
public class AppointmentForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ReceptionForm
     */
    public AppointmentForm() {
        initComponents();
        loadSystemDate();
        loadSystemTime();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void load() {
        try {
            UnicastRemoteObject.exportObject(this, 0);
            AppointmentController.registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(AppointmentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblAppointmentList = new javax.swing.JLabel();
        lblMakeAppointment = new javax.swing.JLabel();
        lblManageAppointment = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlLayOut = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-minimize-window-40 (1).png"))); // NOI18N
        lblMinimize.setText("jLabel3");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        TitlePanel.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 40));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-close-window-40.png"))); // NOI18N
        lblClose.setText("jLabel3");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        TitlePanel.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Minion Pro Cond", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                        Suwasewana");
        jLabel1.setOpaque(true);
        TitlePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 3, 1090, 130));

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 130));

        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/home.png"))); // NOI18N
        lblHome.setText("jLabel3");
        lblHome.setOpaque(true);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        ButtonPanel.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 50));

        lblAppointmentList.setBackground(new java.awt.Color(255, 255, 255));
        lblAppointmentList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAppointmentList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-list-40 (4).png"))); // NOI18N
        lblAppointmentList.setText("Appointment List");
        lblAppointmentList.setOpaque(true);
        lblAppointmentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppointmentListMouseClicked(evt);
            }
        });
        ButtonPanel.add(lblAppointmentList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 60));

        lblMakeAppointment.setBackground(new java.awt.Color(255, 255, 255));
        lblMakeAppointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMakeAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-add-property-40 (1).png"))); // NOI18N
        lblMakeAppointment.setText("Make Appointment");
        lblMakeAppointment.setOpaque(true);
        lblMakeAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakeAppointmentMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMakeAppointmentMouseReleased(evt);
            }
        });
        ButtonPanel.add(lblMakeAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, 60));

        lblManageAppointment.setBackground(new java.awt.Color(255, 255, 255));
        lblManageAppointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-edit-file-40.png"))); // NOI18N
        lblManageAppointment.setText("ManageAppointment");
        lblManageAppointment.setOpaque(true);
        lblManageAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageAppointmentMouseClicked(evt);
            }
        });
        ButtonPanel.add(lblManageAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, 60));

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setOpaque(true);
        ButtonPanel.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 30));

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setOpaque(true);
        ButtonPanel.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-15, 3, 230, 710));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 710));

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLayOut.setBackground(new java.awt.Color(255, 255, 255));
        pnlLayOut.setLayout(new java.awt.CardLayout());
        MainPanel.add(pnlLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 1090, 580));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMakeAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeAppointmentMouseClicked
        pnlAppointment a = new pnlAppointment();
        pnlLayOut.removeAll();
        pnlLayOut.add(a);
        pnlLayOut.repaint();;
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeAppointmentMouseClicked

    private void lblManageAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageAppointmentMouseClicked
        PnlManageAppointment m = new PnlManageAppointment();
        pnlLayOut.removeAll();
        pnlLayOut.add(m);
        pnlLayOut.repaint();;
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblManageAppointmentMouseClicked

    private void lblAppointmentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppointmentListMouseClicked
        pnlListOfAppointment l = new pnlListOfAppointment();
        pnlLayOut.removeAll();
        pnlLayOut.add(l);
        pnlLayOut.repaint();;
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAppointmentListMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        
        try {
            AppointmentController.unRegisterObserver(this);
            ReceptionHome r = new ReceptionHome();
            r.setVisible(true);
            this.dispose();
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(AppointmentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit?");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMakeAppointmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeAppointmentMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeAppointmentMouseReleased

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBackground(Color.gray);
        lblHome.setSize(60, 60);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBackground(Color.white);
        lblHome.setSize(50, 50);
    }//GEN-LAST:event_lblHomeMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAppointmentList;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMakeAppointment;
    private javax.swing.JLabel lblManageAppointment;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlLayOut;
    // End of variables declaration//GEN-END:variables

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String DateFormat = df.format(d1);
        lblDate.setText(DateFormat);
    }

    private void loadSystemTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss ");
                String DateFormat = df.format(d1);
                lblTime.setText(DateFormat);
            }
        }).start();
    }

    @Override
    public void update() throws Exception {
            JOptionPane.showMessageDialog(rootPane, "Another user change some data..!");
    }
}
