/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class DoctorForm extends javax.swing.JFrame {

    /**
     * Creates new form DoctorForm
     */
    public DoctorForm() {
        initComponents();
        loadSystemDate();
        loadSystemTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        lblminimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        lblDoctorLst = new javax.swing.JLabel();
        lblAddDoctor = new javax.swing.JLabel();
        lblManageDoctor = new javax.swing.JLabel();
        lblFindDoctor = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlLayOut = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-minimize-window-40 (1).png"))); // NOI18N
        lblminimize.setText("jLabel3");
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
        });
        TitlePanel.add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 40));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-close-window-40.png"))); // NOI18N
        lblClose.setText("jLabel3");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        TitlePanel.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Minion Pro Cond", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                        Suwasewana");
        jLabel1.setOpaque(true);
        TitlePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 3, 1090, 130));

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 130));

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setOpaque(true);
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 30));

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setOpaque(true);
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 30));

        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDoctorLst.setBackground(new java.awt.Color(255, 255, 255));
        lblDoctorLst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDoctorLst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-list-40 (4).png"))); // NOI18N
        lblDoctorLst.setText("Doctor List");
        lblDoctorLst.setOpaque(true);
        lblDoctorLst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctorLstMouseClicked(evt);
            }
        });
        ButtonPanel.add(lblDoctorLst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 190, 60));

        lblAddDoctor.setBackground(new java.awt.Color(255, 255, 255));
        lblAddDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Add User Male_48px_1.png"))); // NOI18N
        lblAddDoctor.setText("Add Doctor");
        lblAddDoctor.setToolTipText("AddDoctor");
        lblAddDoctor.setOpaque(true);
        lblAddDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddDoctorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddDoctorMouseEntered(evt);
            }
        });
        ButtonPanel.add(lblAddDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, 60));

        lblManageDoctor.setBackground(new java.awt.Color(255, 255, 255));
        lblManageDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-edit-file-40.png"))); // NOI18N
        lblManageDoctor.setText("Manage Doctor");
        lblManageDoctor.setOpaque(true);
        lblManageDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageDoctorMouseClicked(evt);
            }
        });
        ButtonPanel.add(lblManageDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, 60));

        lblFindDoctor.setBackground(new java.awt.Color(255, 255, 255));
        lblFindDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFindDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-search-30.png"))); // NOI18N
        lblFindDoctor.setText("Find Doctor");
        lblFindDoctor.setOpaque(true);
        lblFindDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFindDoctorMouseClicked(evt);
            }
        });
        ButtonPanel.add(lblFindDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 190, 60));

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/home.png"))); // NOI18N
        lblHome.setText("jLabel3");
        lblHome.setOpaque(true);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        ButtonPanel.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-15, 3, 230, 710));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 710));

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLayOut.setBackground(new java.awt.Color(255, 255, 255));
        pnlLayOut.setLayout(new java.awt.CardLayout());
        MainPanel.add(pnlLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 1090, 580));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit?");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblDoctorLstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorLstMouseClicked
        PnlFindDoctor l = new PnlFindDoctor();
        pnlLayOut.removeAll();
        pnlLayOut.add(l);
        pnlLayOut.repaint();;
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDoctorLstMouseClicked

    private void lblAddDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddDoctorMouseClicked
        PnlAddDoctor a = new PnlAddDoctor();
        pnlLayOut.removeAll();
        pnlLayOut.add(a);
        pnlLayOut.repaint();
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddDoctorMouseClicked

    private void lblManageDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageDoctorMouseClicked
        pnlManageDoctor m = new pnlManageDoctor();
        pnlLayOut.removeAll();
        pnlLayOut.add(m);
        pnlLayOut.repaint();
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblManageDoctorMouseClicked

    private void lblFindDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFindDoctorMouseClicked
        PnlListOfDoctors m = new PnlListOfDoctors();
        pnlLayOut.removeAll();
        pnlLayOut.add(m);
        pnlLayOut.repaint();
        pnlLayOut.revalidate();
        pnlLayOut.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_lblFindDoctorMouseClicked

    private void lblAddDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddDoctorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddDoctorMouseEntered

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        this.setVisible(false);
        ReceptionHome r = new ReceptionHome();
        r.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBackground(Color.gray);
        lblHome.setSize(60,60);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBackground(Color.white);
        lblHome.setSize(50,50);
    }//GEN-LAST:event_lblHomeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAddDoctor;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctorLst;
    private javax.swing.JLabel lblFindDoctor;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblManageDoctor;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JPanel pnlLayOut;
    // End of variables declaration//GEN-END:variables

    private void loadSystemTime() {
        new javax.swing.Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss ");
                String DateFormat = df.format(d1);
                lblTime.setText(DateFormat);
            }
        }).start();
    }

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String DateFormat = df.format(d1);
        lblDate.setText(DateFormat);
    }
}
