/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.AppointmentController;
import lk.ijse.pos.controller.DoctorController;
import lk.ijse.pos.controller.PatientControlller;
import lk.ijse.pos.controller.ReceptionController;
import lk.ijse.pos.dto.AppointmentDTO;
import lk.ijse.pos.dto.DoctorDTO;
import lk.ijse.pos.dto.PatientDTO;
import lk.ijse.pos.dto.ReceptionDTO;
import lk.ijse.pos.valid.Validation;

/**
 *
 * @author DEll
 */
public class pnlAppointment extends javax.swing.JPanel {

    /**
     * Creates new form pnlAppointment
     */
    public pnlAppointment() {
        initComponents();
        loadDoctorNames();
        loadReceptions();
        txtAppId.setVisible(false);
        txtReceptionID.setVisible(false);
        txtDoctorID.setVisible(false);
        txtPatientID.setVisible(false);
        txtPatientName.setVisible(false);
        txtDate.setVisible(false);
        pnlNewPatient.setVisible(false);
        pnlOldPatient.setVisible(false);
        txtGender.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dCAppointmentDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtAppoNo = new javax.swing.JTextField();
        txtReceptionID = new javax.swing.JTextField();
        cmbDoctorName = new javax.swing.JComboBox();
        pnlOldPatient = new javax.swing.JPanel();
        txtPName1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnModifyPatient = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtContact1 = new javax.swing.JTextField();
        lblCloseH1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlNewPatient = new javax.swing.JPanel();
        txtPName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblCloseH = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();
        cmbGender = new javax.swing.JComboBox();
        lblNewPatient = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        pnlAddAppointment = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        lblOldPatient = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbReceptionName = new javax.swing.JComboBox();
        txtDoctorID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAppId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                         Add Appointment");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1090, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Appointment Time");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        txtDoctorId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Appointment Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        dCAppointmentDate.setDateFormatString("yyyy-MM-dd");
        add(dCAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Appointment No");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        txtAppoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppoNoActionPerformed(evt);
            }
        });
        txtAppoNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAppoNoKeyReleased(evt);
            }
        });
        add(txtAppoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 40, 30));

        txtReceptionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceptionIDActionPerformed(evt);
            }
        });
        add(txtReceptionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 30, 20));

        cmbDoctorName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDoctorNameItemStateChanged(evt);
            }
        });
        cmbDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoctorNameActionPerformed(evt);
            }
        });
        add(cmbDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, 30));

        pnlOldPatient.setBackground(new java.awt.Color(153, 153, 255));
        pnlOldPatient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPName1ActionPerformed(evt);
            }
        });
        txtPName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPName1KeyReleased(evt);
            }
        });
        pnlOldPatient.add(txtPName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Address");
        pnlOldPatient.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });
        pnlOldPatient.add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Gender");
        pnlOldPatient.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        btnModifyPatient.setBackground(new java.awt.Color(204, 255, 204));
        btnModifyPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModifyPatient.setForeground(new java.awt.Color(0, 204, 51));
        btnModifyPatient.setText("Modify");
        btnModifyPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyPatientActionPerformed(evt);
            }
        });
        pnlOldPatient.add(btnModifyPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, 30));

        btnCancel1.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        pnlOldPatient.add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Age");
        pnlOldPatient.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        txtAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge1ActionPerformed(evt);
            }
        });
        txtAge1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAge1KeyReleased(evt);
            }
        });
        pnlOldPatient.add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Contact");
        pnlOldPatient.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        txtContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContact1ActionPerformed(evt);
            }
        });
        txtContact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContact1KeyReleased(evt);
            }
        });
        pnlOldPatient.add(txtContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, -1));

        lblCloseH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Error-icon.png"))); // NOI18N
        lblCloseH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseClicked(evt);
            }
        });
        pnlOldPatient.add(lblCloseH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        txtGender.setEditable(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenderKeyReleased(evt);
            }
        });
        pnlOldPatient.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Name");
        pnlOldPatient.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        pnlNewPatient.setBackground(new java.awt.Color(153, 153, 255));
        pnlNewPatient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNameActionPerformed(evt);
            }
        });
        pnlNewPatient.add(txtPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Address");
        pnlNewPatient.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        pnlNewPatient.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Gender");
        pnlNewPatient.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Age");
        pnlNewPatient.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        pnlNewPatient.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Contact");
        pnlNewPatient.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
        });
        pnlNewPatient.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, -1));

        lblCloseH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Error-icon.png"))); // NOI18N
        lblCloseH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseHMouseClicked(evt);
            }
        });
        pnlNewPatient.add(lblCloseH, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Name");
        pnlNewPatient.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        btnCancel.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel");
        pnlNewPatient.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 30));

        btnAddPatient.setBackground(new java.awt.Color(204, 255, 204));
        btnAddPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddPatient.setForeground(new java.awt.Color(0, 204, 51));
        btnAddPatient.setText("Add");
        pnlNewPatient.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 70, 30));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        pnlNewPatient.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 80, -1));

        pnlOldPatient.add(pnlNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 210));

        add(pnlOldPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 340, 210));

        lblNewPatient.setBackground(new java.awt.Color(153, 255, 255));
        lblNewPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Add-Male-User-icon.png"))); // NOI18N
        lblNewPatient.setText("New Patient");
        lblNewPatient.setOpaque(true);
        lblNewPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewPatientMouseClicked(evt);
            }
        });
        add(lblNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Doctor Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        tblAppointments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "No"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, 240));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 54, 54));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 100, 40));

        pnlAddAppointment.setBackground(new java.awt.Color(204, 255, 204));
        pnlAddAppointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlAddAppointment.setForeground(new java.awt.Color(0, 204, 51));
        pnlAddAppointment.setText("Make  Appointment");
        pnlAddAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlAddAppointmentActionPerformed(evt);
            }
        });
        add(pnlAddAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 170, 40));

        lblSearch.setBackground(new java.awt.Color(255, 255, 255));
        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-search-30.png"))); // NOI18N
        lblSearch.setOpaque(true);
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 40, 50));

        lblOldPatient.setBackground(new java.awt.Color(153, 255, 255));
        lblOldPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOldPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Add-Male-User-icon.png"))); // NOI18N
        lblOldPatient.setText("Old Paitent");
        lblOldPatient.setOpaque(true);
        lblOldPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOldPatientMouseClicked(evt);
            }
        });
        add(lblOldPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Reception Name");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, 30));

        cmbReceptionName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbReceptionNameItemStateChanged(evt);
            }
        });
        add(cmbReceptionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 190, 30));

        txtDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIDActionPerformed(evt);
            }
        });
        add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 20));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, -1));
        add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 40, 20));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        txtTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimeKeyReleased(evt);
            }
        });
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, 30));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("08:15 AM - 10:30AM");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, 20));
        add(txtAppId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAppoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppoNoActionPerformed

    private void txtReceptionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceptionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceptionIDActionPerformed

    private void txtPNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPNameActionPerformed
        txtAddress.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtContact.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void lblNewPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewPatientMouseClicked
        pnlNewPatient.setVisible(true);
        pnlOldPatient.setVisible(false);
        lblOldPatient.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewPatientMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cleartTxtfields();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked

        try {
            String doctorName = (String) cmbDoctorName.getSelectedItem();
            Date date = dCAppointmentDate.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formatDate = dateFormat.format(date);
            DefaultTableModel dtm = (DefaultTableModel) tblAppointments.getModel();
            dtm.setRowCount(0);
            List<AppointmentDTO> appointments = AppointmentController.searchAppointments(doctorName, formatDate);
            if (appointments == null) {
                return;
            }
            for (AppointmentDTO appointment : appointments) {
                Object[] rowData = {
                    appointment.getAppDate(),
                    appointment.getAppTime(),
                    appointment.getAppNO()};
                dtm.addRow(rowData);
            }

// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        txtAge.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void lblOldPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOldPatientMouseClicked
        pnlNewPatient.setVisible(false);
        pnlOldPatient.setVisible(true);
        lblNewPatient.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOldPatientMouseClicked

    private void lblCloseHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseHMouseClicked
        pnlNewPatient.setVisible(false);
        lblOldPatient.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseHMouseClicked

    private void txtPName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPName1ActionPerformed
        try {
            boolean reserve = PatientControlller.reservePatient(txtPName1.getText());

            String name = txtPName1.getText();
            PatientDTO patientDTO = PatientControlller.searchByName(name);
            txtPatientID.setText(Integer.toString(patientDTO.getpID()));
            txtPName.setText(patientDTO.getpName());
            txtAddress1.setText(patientDTO.getpAddress());
            txtContact1.setText(patientDTO.getpContact());
            txtAge1.setText(patientDTO.getAge());
            txtGender.setText(patientDTO.getGender());
            PatientControlller.reservePatient(txtPatientID.getText());

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPName1ActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void btnModifyPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyPatientActionPerformed
        try {
            PatientDTO patientDTO = new PatientDTO(Integer.parseInt(txtPatientID.getText()),
                    txtPName1.getText(),
                    txtAddress1.getText(),
                    txtContact1.getText(),
                    txtAge1.getText(),
                    txtGender.getText());
            boolean result = PatientControlller.updatePatient(patientDTO);
            if (result) {
                JOptionPane.showMessageDialog(this, "Patient has been updated successfully");
                boolean release = PatientControlller.releasePatient(txtPName1.getText());
                txtPatientName.setText(txtPName1.getText());
                String name = txtPatientName.getText();
                patientDTO = PatientControlller.searchByName(name);
                txtPatientID.setText(Integer.toString(patientDTO.getpID()));
            } else {
                JOptionPane.showMessageDialog(this, "Patient hasn't been updated successfully");
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifyPatientActionPerformed

    private void txtAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1ActionPerformed

    private void txtContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContact1ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        try {
            boolean release = PatientControlller.releasePatient(txtPName1.getText());
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void lblCloseH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseClicked
        pnlOldPatient.setVisible(false);
        lblNewPatient.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseH1MouseClicked

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIDActionPerformed

    private void cmbDoctorNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDoctorNameItemStateChanged
        try {
            String name = (String) cmbDoctorName.getSelectedItem();
            DoctorDTO doctorDTO = DoctorController.findByName(name);
            txtDoctorID.setText(Integer.toString(doctorDTO.getdID()));
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDoctorNameItemStateChanged

    private void cmbReceptionNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbReceptionNameItemStateChanged
        try {
            String name = (String) cmbReceptionName.getSelectedItem();
            ReceptionDTO receptionDTO = ReceptionController.searchReception(name);
            txtReceptionID.setText(Integer.toString(receptionDTO.getrID()));
// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbReceptionNameItemStateChanged

    private void pnlAddAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlAddAppointmentActionPerformed
        try {
            Date date1 = dCAppointmentDate.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formatDate = dateFormat.format(date1);

            AppointmentDTO appointmentDTO = new AppointmentDTO(Integer.parseInt(txtPatientID.getText()),
                    Integer.parseInt(txtReceptionID.getText()),
                    Integer.parseInt(txtDoctorID.getText()),
                    formatDate,
                    txtTime.getText(),
                    //JSpinner.getValue() + ":" + cmbTime.getSelectedItem(),
                    txtAppoNo.getText(),
                    txtPatientName.getText(),
                    (String) cmbDoctorName.getSelectedItem());
            AppointmentController.reserveAppointment(txtAppoNo.getText());

            boolean result = AppointmentController.addAppointment(appointmentDTO);
            if (result) {
                JOptionPane.showMessageDialog(this, "Appointment has been added successfully");
                cleartTxtfields();

            } else {
                JOptionPane.showMessageDialog(this, "Appointment hasn't been added successfully");
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlAddAppointmentActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeKeyReleased

    private void txtAppoNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppoNoKeyReleased
        Validation.numberOnly(txtAppoNo);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppoNoKeyReleased

    private void txtPName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPName1KeyReleased
        Validation.name(txtPName);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPName1KeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased
        Validation.phoneNumber(txtContact);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        Validation.numberOnly(txtAge);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtContact1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContact1KeyReleased
        Validation.phoneNumber(txtContact1);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContact1KeyReleased

    private void txtAge1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAge1KeyReleased
        Validation.numberOnly(txtAge1);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1KeyReleased

    private void txtGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderKeyReleased

    private void cmbDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDoctorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnModifyPatient;
    private javax.swing.JComboBox cmbDoctorName;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbReceptionName;
    private com.toedter.calendar.JDateChooser dCAppointmentDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCloseH;
    private javax.swing.JLabel lblCloseH1;
    private javax.swing.JLabel lblNewPatient;
    private javax.swing.JLabel lblOldPatient;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JButton pnlAddAppointment;
    private javax.swing.JPanel pnlNewPatient;
    private javax.swing.JPanel pnlOldPatient;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtAppId;
    private javax.swing.JTextField txtAppoNo;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContact1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JLabel txtDoctorId;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPName1;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtReceptionID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadDoctorNames() {
        try {
            List<DoctorDTO> doctors = DoctorController.getAllDoctors();
            if (doctors != null) {
                cmbDoctorName.removeAllItems();

            }
            for (DoctorDTO doctor : doctors) {
                cmbDoctorName.addItem(doctor.getdName());
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cleartTxtfields() {
        txtAppoNo.setText("");
        txtTime.setText("");
        txtDoctorID.setText("");
        txtPatientID.setText("");
        txtPatientName.setText("");
        txtReceptionID.setText("");
    }

    private void loadReceptions() {
        try {
            List<ReceptionDTO> receptions = ReceptionController.getAllReceptions();
            if (receptions != null) {
                cmbReceptionName.removeAllItems();

            }
            for (ReceptionDTO reception : receptions) {
                cmbReceptionName.addItem(reception.getrName());
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
