/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.pos.controller.DoctorController;
import lk.ijse.pos.dto.DoctorDTO;

/**
 *
 * @author DEll
 */
public class pnlManageDoctor extends javax.swing.JPanel {

    /**
     * Creates new form pnlManageDoctor
     */
    public pnlManageDoctor() {
        initComponents();
        loadDoctorNames();
        //txtHospitalID.setVisible(false);
        //txtSpecialityID.setVisible(false);
        //txtDoctorID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbDName = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        txtHospital = new javax.swing.JTextField();
        txtSpecialityID = new javax.swing.JTextField();
        txtHospitalID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                         Manage Doctor");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1090, 60));

        btnModify.setBackground(new java.awt.Color(204, 255, 204));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModify.setForeground(new java.awt.Color(0, 204, 51));
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 100, 40));

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 204));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 100, 40));

        btnCancel.setBackground(new java.awt.Color(255, 204, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 0, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 100, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Address");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Contact");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("NIC");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        txtNIC.setEditable(false);
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 190, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Government ID");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 30));

        txtGID.setEditable(false);
        txtGID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGIDActionPerformed(evt);
            }
        });
        add(txtGID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Hospital ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, 30));

        cmbDName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDNameItemStateChanged(evt);
            }
        });
        cmbDName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDNameActionPerformed(evt);
            }
        });
        add(cmbDName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Speciality");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 130, 30));
        add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        txtSpeciality.setEditable(false);
        add(txtSpeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 190, 30));

        txtHospital.setEditable(false);
        add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 30));
        add(txtSpecialityID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 30, 30));

        txtHospitalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalIDActionPerformed(evt);
            }
        });
        add(txtHospitalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try {
            DoctorDTO doctorDTO=new DoctorDTO(Integer.parseInt(txtDoctorID.getText()),
                    (String)cmbDName.getSelectedItem(),
                    Integer.parseInt(txtSpecialityID.getText()),
                    Integer.parseInt(txtHospitalID.getText()),
                    txtGID.getText(),
                    txtAddress.getText(),
                    txtNIC.getText(),
                    txtContact.getText(),
                    txtHospital.getText(),
                    txtSpeciality.getText());
            boolean result=DoctorController.updateDoctor(doctorDTO);
            if (result) {
                JOptionPane.showMessageDialog(this, "Doctor has been Updated successfullly");
                clearTextFields();
            }else{
                JOptionPane.showMessageDialog(this, "Doctor hasn't been Updated sucessfully ");
                clearTextFields();
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlManageDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            boolean result=DoctorController.DeleteDoctor((String) cmbDName.getSelectedItem());
            if (result) {
                JOptionPane.showMessageDialog(this, "Doctor has been deleted successfully");
            }else{
                JOptionPane.showMessageDialog(this, "Doctor has been deleted successfully");
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(pnlManageDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearTextFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtGIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGIDActionPerformed

    private void cmbDNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDNameActionPerformed

    private void cmbDNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDNameItemStateChanged
        try {
            String doctor=(String) cmbDName.getSelectedItem();
            DoctorDTO doctorDTO=DoctorController.findByName(doctor);
            txtDoctorID.setText(Integer.toString(doctorDTO.getdID()));
            txtSpecialityID.setText(Integer.toString(doctorDTO.getSpecialityID()));
            txtHospitalID.setText(Integer.toString(doctorDTO.gethID()));
            txtGID.setText(doctorDTO.getdRNo());
            txtAddress.setText(doctorDTO.getdAddress());
            txtNIC.setText(doctorDTO.getdNIC());
            txtContact.setText(doctorDTO.getdContact());
            txtHospital.setText(doctorDTO.getHospital());
            txtSpeciality.setText(doctorDTO.getSpetiality());
        } catch (Exception ex) {
            Logger.getLogger(pnlManageDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbDNameItemStateChanged

    private void txtHospitalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox cmbDName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtGID;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtHospitalID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtSpecialityID;
    // End of variables declaration//GEN-END:variables

    private void loadDoctorNames() {
        try {
            List<DoctorDTO> doctors = DoctorController.getAllDoctors();
            cmbDName.removeAllItems();
            if (doctors == null) {
                return;
            }

            for (DoctorDTO doctor : doctors) {
                cmbDName.addItem(doctor.getdName());
                System.out.println("12321214312412412");
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlManageDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void clearTextFields(){
        txtContact.setText("");
        txtAddress.setText("");
        txtGID.setText("");
        txtHospital.setText("");
        txtNIC.setText("");
        txtSpeciality.setText("");
    }
}
