/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.pos.controller.ReceptionController;
import lk.ijse.pos.dto.ReceptionDTO;

/**
 *
 * @author DEll
 */
public class ReceptionHome extends javax.swing.JFrame {

    private String name;

    public ReceptionHome() {

    }

    public ReceptionHome(String name) {
        this.name = name;
        initComponents();
        pnlUpdateReception.setVisible(false);
        loadReceptions();
        lblAppoiintment.setBackground(new Color(255, 255, 255, 150));
        lblDoctor.setBackground(new Color(255, 255, 255, 150));
        lblAttendance.setBackground(new Color(255, 255, 255, 150));
        lblPayment.setBackground(new Color(255, 255, 255, 150));
        lblScedule.setBackground(new Color(255, 255, 255, 150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUpdateReception = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtReceptionID = new javax.swing.JTextField();
        pnlReceptionHome = new javax.swing.JPanel();
        lblAppoiintment = new javax.swing.JLabel();
        lblAttendance = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblScedule = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        lblCloseH1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUpdateReception.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpdateReception.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("                           Add new Receptionist");
        jLabel4.setOpaque(true);
        pnlUpdateReception.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1090, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Name");
        pnlUpdateReception.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Address");
        pnlUpdateReception.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Contact");
        pnlUpdateReception.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Password");
        pnlUpdateReception.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, 30));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 190, 30));

        btnModify.setBackground(new java.awt.Color(153, 153, 255));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModify.setForeground(new java.awt.Color(0, 0, 204));
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 54, 54));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, 40));

        cmbName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNameItemStateChanged(evt);
            }
        });
        cmbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameActionPerformed(evt);
            }
        });
        pnlUpdateReception.add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-undo-96.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        pnlUpdateReception.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 80));
        pnlUpdateReception.add(txtReceptionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 40, 30));

        getContentPane().add(pnlUpdateReception, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        pnlReceptionHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAppoiintment.setBackground(new java.awt.Color(82, 179, 217));
        lblAppoiintment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAppoiintment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-stethoscope-80.png"))); // NOI18N
        lblAppoiintment.setText("Appointment");
        lblAppoiintment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAppoiintment.setOpaque(true);
        lblAppoiintment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppoiintmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAppoiintmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAppoiintmentMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblAppoiintment, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 270, 110));

        lblAttendance.setBackground(new java.awt.Color(82, 179, 217));
        lblAttendance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-pass-fail-96.png"))); // NOI18N
        lblAttendance.setText("Attendance");
        lblAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAttendance.setOpaque(true);
        lblAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 270, 110));

        lblDoctor.setBackground(new java.awt.Color(82, 179, 217));
        lblDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Head-Physician-icon.png"))); // NOI18N
        lblDoctor.setText("Doctor");
        lblDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblDoctor.setOpaque(true);
        lblDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoctorMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 270, 110));

        lblScedule.setBackground(new java.awt.Color(82, 179, 217));
        lblScedule.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblScedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-calendar-96.png"))); // NOI18N
        lblScedule.setText("Schedule");
        lblScedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblScedule.setOpaque(true);
        lblScedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSceduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSceduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSceduleMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblScedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, 110));

        lblPayment.setBackground(new java.awt.Color(82, 179, 217));
        lblPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-payment-history-80.png"))); // NOI18N
        lblPayment.setText("Payment");
        lblPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPayment.setOpaque(true);
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 270, 110));

        lblCloseH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/Error-icon.png"))); // NOI18N
        lblCloseH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseH1MouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblCloseH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 30, 30));

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Reception Portal");
        jLabel2.setOpaque(true);
        pnlReceptionHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 890, 50));

        lblSettings.setBackground(new java.awt.Color(204, 255, 255));
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/icons8-services-48.png"))); // NOI18N
        lblSettings.setToolTipText("Settings");
        lblSettings.setOpaque(true);
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });
        pnlReceptionHome.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/resources/1618596.jpg"))); // NOI18N
        pnlReceptionHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 900, 610));

        getContentPane().add(pnlReceptionHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAppoiintmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppoiintmentMouseClicked
        AppointmentForm a = new AppointmentForm();
        this.setVisible(false);
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAppoiintmentMouseClicked

    private void lblAppoiintmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppoiintmentMouseEntered
        lblAppoiintment.setSize(280, 120);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAppoiintmentMouseEntered

    private void lblAppoiintmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppoiintmentMouseExited
        lblAppoiintment.setSize(270, 110);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAppoiintmentMouseExited

    private void lblAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseClicked
        AttendanceForm a = new AttendanceForm();
        this.setVisible(false);
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAttendanceMouseClicked

    private void lblAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseEntered
        lblAttendance.setSize(280, 120);
    }//GEN-LAST:event_lblAttendanceMouseEntered

    private void lblAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseExited
        lblAttendance.setSize(270, 110);
    }//GEN-LAST:event_lblAttendanceMouseExited

    private void lblDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorMouseClicked
        DoctorForm d = new DoctorForm();
        this.setVisible(false);
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDoctorMouseClicked

    private void lblDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorMouseEntered
        lblDoctor.setSize(280, 120);
    }//GEN-LAST:event_lblDoctorMouseEntered

    private void lblDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorMouseExited
        lblDoctor.setSize(270, 110);
    }//GEN-LAST:event_lblDoctorMouseExited

    private void lblSceduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSceduleMouseClicked
        ScheduleForm s = new ScheduleForm();
        this.setVisible(false);
        s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSceduleMouseClicked

    private void lblSceduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSceduleMouseEntered
        lblScedule.setSize(280, 120);
    }//GEN-LAST:event_lblSceduleMouseEntered

    private void lblSceduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSceduleMouseExited
        lblScedule.setSize(270, 110);
    }//GEN-LAST:event_lblSceduleMouseExited

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        PaymentForm p = new PaymentForm();
        this.setVisible(false);
        p.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered
        lblPayment.setSize(280, 120);
    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited
        lblPayment.setSize(270, 110);
    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        pnlUpdateReception.setVisible(true);
        pnlReceptionHome.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtContact.requestFocus();
        txtContact.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        txtPassword.requestFocus();
        txtPassword.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        btnModify.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try {
            ReceptionDTO receptionDTO = new ReceptionDTO(Integer.parseInt(txtReceptionID.getText()),
                    (String) cmbName.getSelectedItem(),
                    txtAddress.getText(),
                    txtContact.getText(),
                    txtPassword.getText());
            boolean result = ReceptionController.updateReception(receptionDTO);
            if (result) {
                JOptionPane.showMessageDialog(this, "Receptionist has been updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Receptionist hasn't been updated successfully");
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ReceptionHome.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModifyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtAddress.setText("");
        txtContact.setText("");
        txtPassword.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        pnlUpdateReception.setVisible(false);
        pnlReceptionHome.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void cmbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameActionPerformed

    private void cmbNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNameItemStateChanged
        try {
            String name = (String) cmbName.getSelectedItem();
            ReceptionDTO receptionDTO = ReceptionController.searchReception(name);
            txtReceptionID.setText(Integer.toString(receptionDTO.getrID()));
            txtAddress.setText(receptionDTO.getAddress());
            txtContact.setText(receptionDTO.getContact());
            txtPassword.setText(receptionDTO.getrPassword());
            System.out.println("abcd");

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ReceptionHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbNameItemStateChanged

    private void lblCloseH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseClicked
        try {
            ReceptionController.releaseReception(name);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(ReceptionHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblCloseH1MouseClicked

    private void lblCloseH1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseEntered
        lblCloseH1.setSize(35, 35);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseH1MouseEntered

    private void lblCloseH1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseH1MouseExited
        lblCloseH1.setSize(30, 30);
    }//GEN-LAST:event_lblCloseH1MouseExited

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        lblSettings.setSize(70, 60);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited
        lblSettings.setSize(80, 70);
    }//GEN-LAST:event_lblSettingsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox cmbName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAppoiintment;
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblCloseH1;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblScedule;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JPanel pnlReceptionHome;
    private javax.swing.JPanel pnlUpdateReception;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtReceptionID;
    // End of variables declaration//GEN-END:variables

    private void loadReceptions() {
        try {
            List<ReceptionDTO> allReceptions = ReceptionController.getAllReceptions();
            cmbName.removeAllItems();
            if (allReceptions == null) {
                return;
            }

            for (ReceptionDTO receptionDTO : allReceptions) {
                cmbName.addItem(receptionDTO.getrName());
            }
        } catch (Exception ex) {
            Logger.getLogger(ReceptionHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
